In [103]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

C:\Users\Mishra\Project


In [104]:
df=pd.read_csv(r"C:\Users\Mishra\Downloads\credit_risk.csv",index_col=0)

In [105]:
df

Age  Income      Home  Emp_length           Intent  Amount   Rate  \
Id                                                                         
0       22   59000      RENT       123.0         PERSONAL   35000  16.02   
1       21    9600       OWN         5.0        EDUCATION    1000  11.14   
2       25    9600  MORTGAGE         1.0          MEDICAL    5500  12.87   
3       23   65500      RENT         4.0          MEDICAL   35000  15.23   
4       24   54400      RENT         8.0          MEDICAL   35000  14.27   
...    ...     ...       ...         ...              ...     ...    ...   
32576   57   53000  MORTGAGE         1.0         PERSONAL    5800  13.16   
32577   54  120000  MORTGAGE         4.0         PERSONAL   17625   7.49   
32578   65   76000      RENT         3.0  HOMEIMPROVEMENT   35000  10.99   
32579   56  150000  MORTGAGE         5.0         PERSONAL   15000  11.48   
32780   66   42000      RENT         2.0          MEDICAL    6475   9.99   

       Status  Percent_income Default  Cred_length  
Id                                                  
0           1            0.59       Y            3  
1           0            0.10       N            2  
2           1            0.57       N            3  
3           1            0.53       N            2  
4           1            0.55       Y            4  
...       ...             ...     ...          ...  
32576       0            0.11       N           30  
32577       0            0.15       N           19  
32578       1            0.46       N           28  
32579       0            0.10       N           26  
32780       0            0.15       N           30  

[32581 rows x 11 columns]

In [106]:
df.describe(include="all")

Age        Income   Home    Emp_length     Intent  \
count   32581.000000  3.258100e+04  32581  31686.000000      32581   
unique           NaN           NaN      4           NaN          6   
top              NaN           NaN   RENT           NaN  EDUCATION   
freq             NaN           NaN  16446           NaN       6453   
mean       27.734600  6.607485e+04    NaN      4.789686        NaN   
std         6.348078  6.198312e+04    NaN      4.142630        NaN   
min        20.000000  4.000000e+03    NaN      0.000000        NaN   
25%        23.000000  3.850000e+04    NaN      2.000000        NaN   
50%        26.000000  5.500000e+04    NaN      4.000000        NaN   
75%        30.000000  7.920000e+04    NaN      7.000000        NaN   
max       144.000000  6.000000e+06    NaN    123.000000        NaN   

              Amount          Rate        Status  Percent_income Default  \
count   32581.000000  29465.000000  32581.000000    32581.000000   32581   
unique           NaN           NaN           NaN             NaN       2   
top              NaN           NaN           NaN             NaN       N   
freq             NaN           NaN           NaN             NaN   26836   
mean     9589.371106     11.011695      0.218164        0.170203     NaN   
std      6322.086646      3.240459      0.413006        0.106782     NaN   
min       500.000000      5.420000      0.000000        0.000000     NaN   
25%      5000.000000      7.900000      0.000000        0.090000     NaN   
50%      8000.000000     10.990000      0.000000        0.150000     NaN   
75%     12200.000000     13.470000      0.000000        0.230000     NaN   
max     35000.000000     23.220000      1.000000        0.830000     NaN   

         Cred_length  
count   32581.000000  
unique           NaN  
top              NaN  
freq             NaN  
mean        5.804211  
std         4.055001  
min         2.000000  
25%         3.000000  
50%         4.000000  
75%         8.000000  
max        30.000000

In [107]:
df.shape

(32581, 11)

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32581 entries, 0 to 32780
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             32581 non-null  int64  
 1   Income          32581 non-null  int64  
 2   Home            32581 non-null  object 
 3   Emp_length      31686 non-null  float64
 4   Intent          32581 non-null  object 
 5   Amount          32581 non-null  int64  
 6   Rate            29465 non-null  float64
 7   Status          32581 non-null  int64  
 8   Percent_income  32581 non-null  float64
 9   Default         32581 non-null  object 
 10  Cred_length     32581 non-null  int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 3.0+ MB


In [109]:
df.Rate.isnull().sum()
#there are 3116 null values in Rate column

3116

In [111]:
median_value = df['Rate'].median()
df['Rate'].fillna(median_value, inplace=True) #filling the missing value with the median value of the rate column

In [113]:
df.drop(["Home","Emp_length","Intent"],axis=1,inplace=True)
#droping the cols

In [114]:
df.Default.replace({"N":0,"Y":1},inplace=True)

In [115]:
df.Age.replace(df.Age.mean(),inplace=True)

In [116]:
df.isnull().sum()

Age               0
Income            0
Amount            0
Rate              0
Status            0
Percent_income    0
Default           0
Cred_length       0
dtype: int64

### Creating X and Y

In [118]:
X=df.drop(["Status"],axis=1)
Y=df.Status

In [119]:
X.shape

(32581, 7)

In [120]:
Y.shape

(32581,)

In [121]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

### Train Test Split

In [122]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)#ensuring the class dist ratio is mantained

In [123]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(26064, 7)
(26064,)
(6517, 7)
(6517,)


In [124]:
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10
                               ,criterion="gini",
                               splitter="best",
                               min_samples_leaf=3,
                               min_samples_split=5,
                               max_depth=10,
                               max_leaf_nodes=100)
                               #max_max_features=0.6
#min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
#print(Y_pred)
# print(list(zip(Y_test,Y_pred)))


### LogisticRegression

In [125]:

from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
#min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
#fit the model on the data and predict the values
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)
#print(Y_pred)
# print(list(zip(Y_test,Y_pred)))


In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[4809  248]
 [ 868  592]]
Classification report: 
              precision    recall  f1-score   support

           0       0.85      0.95      0.90      5057
           1       0.70      0.41      0.51      1460

    accuracy                           0.83      6517
   macro avg       0.78      0.68      0.71      6517
weighted avg       0.82      0.83      0.81      6517

Accuracy of the model:  0.8287555623753261


In [127]:
#Reducing type 2 error 

In [128]:
y_pred_prob = classifier.predict_proba(X_test)
y_pred_prob 

array([[0.20807229, 0.79192771],
       [0.97768239, 0.02231761],
       [0.87059328, 0.12940672],
       ...,
       [0.78545759, 0.21454241],
       [0.51957179, 0.48042821],
       [0.67797976, 0.32202024]])

In [129]:
y_pred_class=[]
for value in y_pred_prob[:,1]:
    if value > 0.30:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)

In [130]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,y_pred_class)
print(cfm)
acc=accuracy_score(Y_test, y_pred_class)
print("Accuracy of the model: ",acc)
print("Classification report: ")
print(classification_report(Y_test,y_pred_class))

[[4286  771]
 [ 495  965]]
Accuracy of the model:  0.8057388368881387
Classification report: 
              precision    recall  f1-score   support

           0       0.90      0.85      0.87      5057
           1       0.56      0.66      0.60      1460

    accuracy                           0.81      6517
   macro avg       0.73      0.75      0.74      6517
weighted avg       0.82      0.81      0.81      6517



### XGB

In [131]:
# Import the necessary library
from xgboost import XGBClassifier

# Create an XGBoost classifier object
xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, subsample=0.8, random_state=10)

# Fit the model on the training data
xgb_classifier.fit(X_train, Y_train)

# Predict the values on the test data
Y_pred = xgb_classifier.predict(X_test)


In [132]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[4768  289]
 [ 550  910]]
Classification report: 
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      5057
           1       0.76      0.62      0.68      1460

    accuracy                           0.87      6517
   macro avg       0.83      0.78      0.80      6517
weighted avg       0.87      0.87      0.87      6517

Accuracy of the model:  0.8712597821083321


### RandomForest

In [133]:
# predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=100,
                                          random_state=10, bootstrap=True,
                                         n_jobs=-1)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)

In [134]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[4773  284]
 [ 566  894]]
Classification report: 
              precision    recall  f1-score   support

           0       0.89      0.94      0.92      5057
           1       0.76      0.61      0.68      1460

    accuracy                           0.87      6517
   macro avg       0.83      0.78      0.80      6517
weighted avg       0.86      0.87      0.86      6517

Accuracy of the model:  0.8695718889059383


### Decision Tree

In [135]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(random_state=10,criterion='gini',splitter='best',min_samples_leaf=3,min_samples_split=5,max_depth=10,
                                 max_leaf_nodes=100)#,max_features=0.6)


model_dt.fit(X_train,Y_train)
Y_pred = model_dt.predict(X_test)

In [136]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[4709  348]
 [ 548  912]]
Classification report: 
              precision    recall  f1-score   support

           0       0.90      0.93      0.91      5057
           1       0.72      0.62      0.67      1460

    accuracy                           0.86      6517
   macro avg       0.81      0.78      0.79      6517
weighted avg       0.86      0.86      0.86      6517

Accuracy of the model:  0.8625134264232008


In [ ]:
#Logistic model is giving  0.8057388368881387 accuracy with the least type 2 error among all the models

In [ ]:
#XGB model is giving 0.8712597821083321 accuracy with the 550 type 2 error 

In [ ]:
#RandomForest model is giving 0.8695718889059383 accuracy with the 566 type 2 error

In [ ]:
#DecisionTree model is giving 0.8625134264232008 accuracy with the 548 type 2 error

In [ ]:
# XGBoost is the better model overall because it has higher accuracy, precision, and F1-Score,
# despite a slightly lower recall compared to Logistic Regression.
# It balances correctly predicting both positive and negative classes more effectively, making it the best choice for most scenarios.